services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '8080:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
